# docker-compose.yml
version: '3.8'

services:
  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    container_name: express-be
    ports:
      - 4000:4000
    networks:
      - webnet
  http1-nginx:
    build:
      context: ./http1
      dockerfile: Dockerfile               # nginx Dockerfile 위치 또는 기존 이미지 사용
    container_name: http1-nginx
    depends_on:
      - express
    ports:
      - 10443:443              # HTTPS (HTTP/2)
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    # expose:
    #   - 80
    networks:
      - webnet
  http2-nginx:
    build:
      context: ./http2
      dockerfile: Dockerfile
    container_name: http2-nginx
    depends_on:
      - express
    ports:
      - 20443:443               # HTTPS (HTTP/2)
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    # expose:
    #   - 80
    networks:
      - webnet
  http3-nginx:
    build:
      context: ./http3
      dockerfile: Dockerfile
    container_name: http3-nginx
    depends_on:
      - express
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 30443:443              # HTTPS (HTTP/2)
    # expose:
    #   - 80
    networks:
      - webnet
networks:
  webnet:
    driver: bridge