# docker-compose.yml
version: '3.8'

services:
  http1-nginx:
    build:
      context: ./http1
      dockerfile: Dockerfile               # nginx Dockerfile 위치 또는 기존 이미지 사용
    container_name: http1-nginx
    ports:
      - 10443:443              # HTTPS (HTTP/2)
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./http1/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./static:/var/www/html
    # expose:
    #   - 80
    networks:
      - webnet
  http2-nginx:
    build:
      context: ./http2
      dockerfile: Dockerfile
    container_name: http2-nginx
    ports:
      - 20443:443               # HTTPS (HTTP/2)
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./http2/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./static:/var/www/html
    # expose:
    #   - 80
    networks:
      - webnet
  http3-nginx:
    build:
      context: ./http3
      dockerfile: Dockerfile
    container_name: http3-nginx
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./http3/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./static:/var/www/html
    ports:
      - 30443:443              # HTTPS (HTTP/2)
    # expose:
    #   - 80
    networks:
      - webnet
networks:
  webnet:
    driver: bridge