# docker-compose.yml
version: '3.8'

services:
  http1express:
    build:
      context: ./http1express
      dockerfile: Dockerfile
    container_name: http1-express-app
    ports:
      - 4000:4000
    networks:
      - webnet
  http2express:
    build:
      context: ./http2express      # express/Dockerfile 위치
      dockerfile: Dockerfile
    container_name: http2-express-app
    ports:
      - 4001:4000
    networks:
      - webnet
  http3express:
    build:
      context: ./http3express
      dockerfile: Dockerfile
    container_name: http3-express-app
    ports:
      - 4002:4000
    networks:
      - webnet
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile               # nginx Dockerfile 위치 또는 기존 이미지 사용
    container_name: nginx-http2
    depends_on:
      - http1express
      - http2express
      - http3express
    ports:
      - "80:80"             # HTTP
      - "443:443"           # HTTPS (HTTP/2)
    networks:
      - webnet
networks:
  webnet:
    driver: bridge